name: Build OpenWrt Firmware with Plugins

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrt/imagebuilder:latest
      options: --user 1000:1000

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up OpenWrt build environment
      run: |
        mkdir -p /workspace/openwrt
        cp -r . /workspace/openwrt
        cd /workspace/openwrt

        # 如果需要修改 feeds 配置，可以在这里进行修改
        echo "src/gz openwrt_core http://downloads.openwrt.org/snapshots/targets/x86/64/packages" >> /etc/opkg/feeds.conf.default
        echo "src/gz openwrt_packages http://downloads.openwrt.org/snapshots/packages/x86_64/packages" >> /etc/opkg/feeds.conf.default
        opkg update

        # 选择插件或包
        # 这里以 luci-app-sqm 为例，可以添加其他插件或者自定义插件
        echo "luci-app-sqm" >> /workspace/openwrt/package/feeds/luci/luci-app-sqm/Makefile

        # 更新并安装插件，确保插件被包含
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run imagebuilder to build firmware
      run: |
        cd /workspace/openwrt
        make firmware

    - name: Upload built firmware
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-firmware
        path: ./bin/targets/*/openwrt-*.img