name: OpenWrt Builder

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 仅在 main 分支推送时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull OpenWrt ImageBuilder
      run: |  
        docker pull openwrt/imagebuilder:x86-64-openwrt-24.10

    - name: Run ImageBuilder inside Docker
      run: |
        docker run --rm -i \
          --user root \
          -v ${{ github.workspace }}/bin:/home/build/openwrt/bin \
          -v ${{ github.workspace }}/buildstart/build.sh:/home/build/openwrt/build.sh \
          openwrt/imagebuilder:x86-64-openwrt-24.10 /bin/bash /home/build/openwrt/build.sh

    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: bin/
